### ISSUE TITLE
Match not found

### ISSUE THREAD

**Issue by Iijil1** [FransFaase/SymbolicTM#2]
SymbolicTM doesn't find a match for "E: 0@10 1 101101(001)\*0@" despite "E: (0)@(10)\* 1 1(01)\*101(001)\*(0)@" being in the file I'm reading. Is that expected behavior with the way you find the matches?

**Comment by FransFaase** [comment]
The general problem of matching two regular expressions is rather complex. I have so far only implemented a number of simple cases. It looks like the example you give should match. I have no idea why it does not match. I will look into it.

**Comment by FransFaase** [comment]
The above commit should fix the issue. (Please reopen if this is not the case.)

This fix does does not find a match for "E: 0@10 1 101101(001)\*0@" if there would be a "E: (0)@(10)\* 1 1(01\*)\*101(001)*(0)@" in the file. (To just give an example of why matching two regular expressions is complex.)
